# Generated by Django 4.0.1 on 2022-09-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_category_prod_updated_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='tienda/sinImagen.jpg', null=True, upload_to='tienda'),
        ),
    ]
