# Generated by Django 4.0.1 on 2022-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='tienda/sin_imagen.png', null=True, upload_to='tienda'),
        ),
    ]
