# Generated by Django 4.0.1 on 2022-10-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='line_order',
            old_name='product_id',
            new_name='product',
        ),
    ]
